services:
  rockscraper-crawl-service:
#    image: crawl/crawl:v0
    build: .
    volumes:
      - ./:/rockscraper-crawl-service
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    ipc: host
    security_opt:
      - seccomp=./seccomp_profile.json
  postgres:
    image: postgres:16.2-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
#  redis:
#      image: redis:6
#      ports:
#        - "6379:6379"
#      command: redis-server --appendonly yes
volumes:
  db: